version: 2
jobs:
  build:
    docker:
      - image: cypress/base:6
        environment:
          TERM: xterm

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test

      - run: ./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls

      - run: node integration.js
